# Cloudflare Pages Configuration
name = "agent-builder-application"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "service-worker"
dir = "dist"
main = "./dist/index.html"

[[pages_build_output_dir]]
value = "dist"
