AWSTemplateFormatVersion: '2010-09-09'
Description: 'Agent Builder Platform - User Account Onboarding (Tier 2)'

Parameters:
  PlatformAccountId:
    Type: String
    Description: The AWS Account ID of the Agent Builder Platform
    AllowedPattern: '[0-9]{12}'
    ConstraintDescription: Must be a valid 12-digit AWS Account ID

  UserIdentifier:
    Type: String
    Description: Your email or unique identifier (used as External ID for security)
    Default: ''

  ProjectName:
    Type: String
    Description: Project name for resource tagging
    Default: 'agent-builder'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Platform Configuration'
        Parameters:
          - PlatformAccountId
          - UserIdentifier
          - ProjectName
    ParameterLabels:
      PlatformAccountId:
        default: 'Platform AWS Account ID'
      UserIdentifier:
        default: 'Your Email or User ID'
      ProjectName:
        default: 'Project Name'

Resources:
  # S3 Bucket for agent artifacts
  AgentArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${AWS::AccountId}-artifacts'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-artifacts'
        - Key: ManagedBy
          Value: 'CloudFormation'

  # CloudWatch Log Group
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/agentcore/${ProjectName}/agents'
      RetentionInDays: 7

  # Cross-Account IAM Role
  CrossAccountRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-cross-account-role'
      Description: Allows Agent Builder Platform to deploy agents to this account
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${PlatformAccountId}:root'
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref UserIdentifier
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-cross-account-role'

  # Deployment Policy
  DeploymentPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${ProjectName}-deployment-policy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: BedrockPermissions
            Effect: Allow
            Action:
              - bedrock:CreateAgent
              - bedrock:CreateAgentActionGroup
              - bedrock:InvokeAgent
              - bedrock:InvokeModel
              - bedrock:InvokeModelWithResponseStream
              - bedrock:GetAgent
              - bedrock:ListAgents
              - bedrock:UpdateAgent
              - bedrock:DeleteAgent
            Resource: '*'

          - Sid: S3Permissions
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource:
              - !GetAtt AgentArtifactsBucket.Arn
              - !Sub '${AgentArtifactsBucket.Arn}/*'

          - Sid: LogsPermissions
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogStreams
            Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/agentcore/${ProjectName}/*'

          - Sid: IAMPermissions
            Effect: Allow
            Action:
              - iam:CreateRole
              - iam:AttachRolePolicy
              - iam:PassRole
              - iam:GetRole
            Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${ProjectName}-*'
      Roles:
        - !Ref CrossAccountRole

Outputs:
  RoleArn:
    Description: Cross-account role ARN (paste this in Agent Builder Platform)
    Value: !GetAtt CrossAccountRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'

  ExternalId:
    Description: External ID for security (paste this in Agent Builder Platform)
    Value: !Ref UserIdentifier
    Export:
      Name: !Sub '${AWS::StackName}-ExternalId'

  Region:
    Description: AWS Region
    Value: !Ref AWS::Region
    Export:
      Name: !Sub '${AWS::StackName}-Region'

  ArtifactsBucketName:
    Description: S3 bucket for agent artifacts
    Value: !Ref AgentArtifactsBucket
    Export:
      Name: !Sub '${AWS::StackName}-ArtifactsBucket'

  SetupInstructions:
    Description: Next steps
    Value: 'Copy the RoleArn and ExternalId above and paste them in the Agent Builder Platform settings under "Connect My AWS Account"'
